function [ monthName ] = getMonthNameFromCode( monthCode )
    codeDict = struct('jan', 'january', 'feb', 'february', 'mar', 'march', ...
                      'apr', 'april',   'may', 'may',      'jun', 'june', ...
                      'jul', 'july',    'aug', 'august',   'sep', 'september', ...
                      'oct', 'october', 'nov', 'november', 'dec', 'december');
    monthName = codeDict.(monthCode);
end

