function [ modality ] = humanReadableModality( keyCode )
    modalityDict = { {'CR',         'Computed Radiography'}, ...
                     {'MR',         'Magnetic Resonance'}, ...
                     {'CT',         'Computed Tomography'}, ...
                     {'NM',         'Nuclear Medecine'}, ...
                     {'US',         'Ultrasound'}, ...
                     {'OT',         'Other'}, ...
                     {'BI',         'Biomagnetic imaging'}, ...
                     {'DG',         'Diaphanography'}, ...
                     {'ES',         'Endoscopy'}, ...
                     {'LS',         'Laser surface scan'}, ...
                     {'PT',         'Positron emission tomography'}, ...
                     {'RG',         'Radiographic imaging'}, ...
                     {'TG',         'Thermography'}, ...
                     {'XA',         'X-Ray angiography'}, ...
                     {'RF',         'Radio Fluoroscopy'}, ...
                     {'RTIMAGE',    'Radiotherapy image'}, ...
                     {'RTDOSE',     'Radiotherapy Dose'}, ...
                     {'RTSTRUCT',   'Radiotherapy Structure Set'}, ...
                     {'RTPLAN',     'Radiotherapy plan'}, ...
                     {'RTRECORD',   'Radiotherapy Treatment Record'}, ...
                     {'HC',         'Hard Copy'}, ...
                     {'DX',         'Digital Radiography'}, ...
                     {'MG',         'Mammography'}, ...
                     {'IO',         'Intra-oral Radiography'}, ...
                     {'PX',         'Panoramic X-Ray'}, ...
                     {'GM',         'General Microscopy'}, ...
                     {'SM',         'Slide Microscopy'}, ...
                     {'XC',         'External-camera Photography'}, ...
                     {'PR',         'Presentation State'}, ...
                     {'AU',         'Audio'}, ...
                     {'ECG',        'Electrocardiography'}, ...
                     {'EPS',        'Cardiac Electrophysiology'}, ...
                     {'HD',         'Hemodynamic Waveform'}, ...
                     {'SR',         'Structured Report Document'}, ...
                     {'IVUS',       'Intravascular Ultrasound'}, ...
                     {'OP',         'Ophthalmic Photography'}, ...
                     {'SMR',        'Stereometric Relationship'}, ...
                     {'AR',         'Autorefraction'}, ...
                     {'KER',        'Keratometry'}, ...
                     {'VA',         'Visual Acuity'}, ...
                     {'SRF',        'Subjective Refraction'}, ...
                     {'OCT',        'Optical Coherence Tomography'}, ...
                     {'LEN',        'Lensometry'}, ...
                     {'OPV',        'Ophthalmic Visual Field'}, ...
                     {'OPM',        'Ophthalmic Mapping'}, ...
                     {'OAM',        'Ophthalmic Axis Measurments'}, ...
                     {'RESP',       'Respiratory Waveform'}, ...
                     {'KO',         'Key Object Selection'}, ...
                     {'SEG',        'Segmentation'}, ...
                     {'REG',        'Registration'}, ...
                     {'OPT',        'Ophthalmic Tomography'}, ...
                     {'BDUS',       'Bone Densiometry Ultrasound'}, ...
                     {'BMD',        'Bone Densiometry X-Ray'}, ...
                     {'DOC',        'Document'}, ...
                     {'FID',        'Fiducials'}, ...
                     {'PLAN',       'Plan'}, ...
                     {'IOL',        'Intraocular Lens Data'}, ...
                     {'IVOCT',      'Intravascular Optical Coherence Tomography'} ...
                   };
               
    modality = modalityDict{find(cellfun(@(x) strcmp(x{1},keyCode), modalityDict))}{2};
end

